### ISSUE TITLE
language selection file?

### ISSUE THREAD

**Issue by djswirl** [MaximumOctopus/LEDMatrixStudio#4]
Hi

Firstly, love this app, thanks for making it !!
Ive downloaded it to have a go at leaning more about C++, and play with LEDS, it complies OK but as noted in your read me the language selection is not working.
After a bit of poking about, in LanguageHandler.cpp line 39 it seems to be trying to open a file. If I understand this correctly there should be a file called something like ENG.txt that has a list of the English words to add to the menus, but I can’t find any file.
What am I missing here?
Thanks

**Comment by djswirl** [comment]
Forget the above, found it in the LEDMatrixStudio_20_22_beta folder and copied it over

**Comment by MaximumOctopus** [comment]
Glad you got it sorted. If you have any other questions don't hesitate to send me an email :)

**Comment by djswirl** [comment]
I love the program! There are so many ideas and questions, but I will wait until you have finished the rewrite. 
Quick question, in the Delphi version when you select optimise output you could get an array with colour indexes (0.1,2,3 ...) doesn't seem to work in this version, but not sure if you have finished that part yet.

I would be happy to bug test for you once you are ready

I would love to see a fastled single array output with colour indexes. This way I can use the code below I'm working on where I can use a colour array or pallett 




#define ARRAY_SIZE(A) (sizeof(A) / sizeof((A)[0])) // for Arrays

const CRGB colour0[] = { CRGB::Black, CRGB::Red, CRGB::Yellow, CRGB::Magenta, CRGB::Green, CRGB::Red, CRGB::Yellow, CRGB::Magenta, CRGB::Green, CRGB::Cyan, CRGB::LightBlue };


void framesByPallett(const uint8_t* frameAry, CRGBPalette16 current, uint8_t indexStep, TBlendType blending)
{
	static uint16_t NUM_FRAMES = ARRAY_SIZE(frameAry) / NUM_LEDS;
	static uint16_t frameNum = 0;
	static uint8_t pallettIndex = 0;
	static uint8_t colourIndex = 0;
	frameNum = (frameNum + 1) % NUM_FRAMES;
	for (int i = 0; i < NUM_LEDS; i++)
	{
		uint8_t frameColour = pgm_read_byte(&frameAry[(frameNum * NUM_LEDS) + i]); // get colour index from frame
colourIndex = pallettIndex + (indexStep * frameColour);
leds[i] = ColorFromPalette(currentPalette, colourIndex, GLOBAL_BRIGHTNESS, blending);
pallettIndex = pallettIndex + indexStep;
}

void framesByColourAry(const uint8_t* frameAry, const CRGB* colourAry)
{
	uint16_t NUM_FRAMES = ARRAY_SIZE(frameAry) / NUM_LEDS;
	static uint16_t frameNum = 0;
	frameNum = (frameNum + 1) % NUM_FRAMES;
	for (int i = 0; i < NUM_LEDS; i++)
		leds[i] = colourAry[pgm_read_byte(&frameAry[(frameNum * NUM_LEDS) + i])];
}
